swagger: '2.0'
info:
  description: Swagger Auth Demo
  title: Swagger Auth Demo
  version: "1.0"
host: 127.0.0.1:8000
basePath: /
tags:
  - name: Swagger Auth Demo
    description: Test protected/public Kong endpoints
schemes:
  - http
paths:
  '/protected':
    get:
      tags:
        - Protected
      summary: Protected Demo Endpoint
      description: 'Protected Demo Endpoint'
      operationId: ProtectedGet
      produces:
        - application/xml
        - application/json
      parameters: []
      responses:
        '200':
          description: successful operation
        '401':
          description: Unauthorized
  '/public':
    get:
      tags:
        - Public
      summary: Public Demo Endpoint
      description: 'Public Demo Endpoint'
      operationId: PublicGet
      produces:
        - application/xml
        - application/json
      parameters: []
      responses:
        '200':
          description: successful operation
        '401':
          description: Unauthorized

securityDefinitions:
  ApiKeyAuth:
    type: apiKey
    in: header
    name: Authorization

security:
  - ApiKeyAuth: []
